name: CBIG_An2022
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35.1
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - curl=7.78.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.3.0
  - gfortran_linux-64=9.3.0
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - harfbuzz=2.8.2
  - icu=68.1
  - jbig=2.1
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - make=4.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pango=1.48.7
  - pcre=8.45
  - pcre2=10.37
  - pip=21.1.3
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.9.5
  - python_abi=3.9
  - r-base=4.1.0
  - r-matrixstats=0.60.0
  - readline=8.1
  - sed=4.8
  - setuptools=52.0.0
  - sqlite=3.36.0
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - tzdata=2021a
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - astroid==2.6.6
    - attrs==21.2.0
    - cffi==1.14.6
    - cycler==0.10.0
    - flake8==3.9.2
    - iniconfig==1.1.1
    - isort==5.9.3
    - jinja2==3.0.1
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.6.0
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - mccabe==0.6.1
    - munkres==1.1.4
    - numpy==1.21.1
    - packaging==21.0
    - pandas==1.1.5
    - pillow==8.3.1
    - pluggy==0.13.1
    - poap==0.1.26
    - py==1.10.0
    - pycodestyle==2.7.0
    - pycparser==2.20
    - pydoe==0.3.8
    - pyflakes==2.3.1
    - pylint==2.9.6
    - pyparsing==2.4.7
    - pytest==6.2.4
    - python-dateutil==2.8.2
    - pytz==2021.1
    - redis==3.5.3
    - rpy2==3.3.6
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - six==1.16.0
    - sklearn==0.0
    - subprocess32==3.5.4
    - threadpoolctl==2.2.0
    - toml==0.10.2
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - "-f https://download.pytorch.org/whl/torch_stable.html"
    - typing-extensions==3.10.0.0
    - tzlocal==2.1
    - wrapt==1.12.1
    - xgboost==1.3.3
    - yapf==0.25.0
